apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
data:
{{- if .Values.config }}
{{- $root := . }}
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ tpl $val $root | indent 4}}
{{- end }}
{{- else }}
  fluent-bit.conf: |-
{{- include "fluent-bit.conf.tpl" . | indent 4 }}
{{- end }}
  parsers.conf: |-
{{- include "parsers.conf.tpl" . | indent 4 }}
